github:
  branch: master
  repository: https://github.com/nvang78/sw-concourse-training.git
  username: nvang78
jobs:
- name: job-upload-release
  plan:
  - config:
      image_resource:
        source:
          repository: starkandwayne/concourse
        type: docker-image
      platform: linux
      run:
        args:
        - Eventually I will upload a bosh release
        path: echo
    task: upload-release
  public: true
meta:
  name: nvang78-nginx-demo
  pipeline: nvang78-nginx-demo
  target: training
  url: https://pipes.starkandwayne.com
release:
  name: nvang78-nginx

